advanced/advanced/urls.py
from django.contrib import admin
from django.urls import path,include
from hotel import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name = 'home'),
    path('hotel/', include('hotel.urls', namespace = 'hotel')),
    path('accounts/login/', auth_views.LoginView.as_view(), name = 'login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('accounts/register/', views.ManagerRegister.as_view(), name = 'register')
]   

advanced/hotel/urls.py
from django.urls import path, re_path
from hotel import views

app_name = 'hotel'

urlpatterns = [
    # rooms urls
    path('', views.RoomsListView.as_view(), name = 'rooms'),
    path('create_room/', views.RoomsCreateView.as_view(), name = 'create_room'),
    re_path(r'^rooms/(?P<pk>\w+)/$', views.RoomsDetailView.as_view(), name = 'room_in_detail'),
    re_path(r'^update/(?P<pk>\w+)/$', views.RoomsUpdateView.as_view(), name = 'update_room'),
    re_path(r'^delete_room(?P<pk>\w+)/$', views.RoomsDeleteView.as_view(), name = 'delete_room'),
    # tenants urls
    re_path(r'^room(?P<pk>\w+)/create_tenant/$', views.TenantsCreateView.as_view(), name = 'create_tenant'),
    re_path(r'^delete_tenant/(?P<pk>\w+)/$', views.TenantsDeleteView.as_view(), name = 'delete_tenant'),
    
]

advanced/hotel/models.py
from django.db import models
from django.core import validators
from django.urls import reverse

# Create your models here.
class Room(models.Model):
    number = models.PositiveIntegerField(primary_key = True)
    floor = models.CharField(max_length = 256)
    capacity = models.PositiveIntegerField(validators = [validators.MaxValueValidator(4,'Must not exceed 4 members')])

    def __str__(self):
        return str(self.number)

    def get_absolute_url(self):
        return reverse("hotel:room_in_detail", kwargs={"pk": self.pk})
    
class Tenant(models.Model):
    student_ID = models.CharField(max_length = 10, primary_key=True)
    name = models.CharField(max_length = 100)
    level = models.PositiveIntegerField()
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name = 'tenants')
    # profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.name 

    def get_absolute_url(self):
        return reverse("hotel:room_in_detail", kwargs={"pk": self.room.pk})


    

advanced/hotel/forms.py
from django import forms
from .models import Tenant

class NewTenantForm(forms.ModelForm):    
    class Meta:
        model = Tenant
        exclude = ('room',) # todo: to prevent editing value in the html (hackily)
        #// widgets = {
        #//     'room' : forms.HiddenInput(attrs={'readonly':True}),
        #// }
    
    # todo: to clean the student_ID field
    def clean_student_ID(self):
        student_id = self.cleaned_data.get('student_ID')
        for i in student_id:
            if i not in '0123456789':
                raise(forms.ValidationError('Student ID must contain only numbers'))
        if len(student_id) != 10:
            raise(forms.ValidationError('student_ID must consist of ten characters'))
        return student_id

    def clean_level(self):
        level = self.cleaned_data['level']
        approved_levels = [100,200,300,400,500,600] 
        if level not in approved_levels:
            raise forms.ValidationError('Please enter a valid level. Eg. 300')
        return level

        

advanced/hotel/views.py
from .models import Tenant, Room
from django.views.generic import ListView, DetailView,TemplateView, CreateView, UpdateView, DeleteView
from .forms import NewTenantForm

from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import request, HttpResponse

from .customs import create_groupings #? custom function for grouping rooms for presentation by RoomsListView

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

class HomeView(TemplateView):
    template_name = 'home.html'
    

class RoomsListView(ListView):
    model = Room
    context_object_name = 'rooms'
    
    group = create_groupings(10) #? dictionary of all rooms in their groupings
    #! let's try using a function based view instead with the function in the model

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["groups"] = self.group
        #// context['objs'] = self.object_list
        return context

class RoomsDetailView(DetailView):
    model = Room
    context_object_name = 'room_in_detail'
    template_name = 'hotel/rooms_details.html'


class RoomsCreateView(CreateView):
    model = Room
    fields = '__all__'


class RoomsUpdateView(UpdateView):
    model = Room
    fields = '__all__'
    

class RoomsDeleteView(DeleteView):
    model = Room
    success_url = reverse_lazy('hotel:rooms')


class TenantsDetailView(DetailView):
    model = Tenant
    context_object_name = 'tenant_in_detail'


class TenantsCreateView(CreateView):
    model = Tenant
    # ? the form_class attribute allows replacement of default CreateView form
    form_class = NewTenantForm

    def form_valid(self, form):
        """
        todo: getting the 'room' variable from the GET request 
        todo: (I created the variable in the url which leads to this view)
        """
        room_num = self.request.GET.get('room')
        # todo: setting the current modelform's room field to the value gotten from above
        form.instance.room = Room.objects.get(number=room_num)
        return super(TenantsCreateView, self).form_valid(form)


class TenantsDeleteView(DeleteView):
    model = Tenant

    # todo: override get_success_url to pass in GET variable as argument for redirection url after object deletion
    def get_success_url(self):
        room_num = self.request.GET['room']
        return reverse_lazy('hotel:room_in_detail', kwargs = {'pk':room_num})

class ManagerRegister(FormView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'

    #? just like (if request.method == 'POST')
    #* def post(self, request, *args, **kwargs):
    #*     return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        self.success_url = reverse_lazy('login')
        form.save()
        return super().form_valid(form)
    
# Alternative function based view
# def ManagerRegister(request):

#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)   

#         if form.is_valid():
#             form.save()
#             return redirect('login')
#     else:
#         form = UserCreationForm()

#     return render(request, 'registration/register.html', {'form':form})

advanced/hotel/templates/hotel/hotel_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %} hotel | Base {% endblock %}</title>

    <link rel="stylesheet" href="{% static 'bs4/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome-free-5.10.1-web/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'hotel.css' %}?v=2">

    
    
</head>

<body>
    <div id="content">
        <nav class="navbar navbar-expand-sm navbar-light bg-light">
            <ul class="navbar-nav nav">
                <li class="nav-item"><a href="{% url 'hotel:rooms' %}" class="nav-link">Rooms</a></li>
                <li class="nav-item"><a href="{% url 'admin:index' %}" class="nav-link">Admin</a></li>
            </ul>
            <ul class="navbar-nav nav" id="user_name">
                <li class="nav-item">
                    logged in as: <a class="nav-link" style = 'display: inline;'>{{ user.username }}</a>
                </li>
            </ul>
        </nav>

        <div class="container-fluid mt-4 " >
            {% block body %}{% endblock %}
            <footer>
                <i class="far fa-copyright"></i> <b>Works of Machele-codez(Codesmith)</b>, Powered by Django 2.2.7 
            </footer>
        </div>
    
    </div>
    
    <script src="{% static 'fontawesome-free-5.10.1-web/js/all.min.js' %}"></script>
    <script src="{% static 'bs4/popper.js' %}?v=2"></script>
    <script src="{% static 'bs4/jquery.js' %}?v=2"></script>
    <script src="{% static 'bs4/js/bootstrap.min.js' %}?v=2"></script>
    
</body>

</html>

advanced/hotel/templates/hotel/room_confirm_delete.html
{% extends 'hotel/hotel_base.html' %}

{% block title %} Delete Room {% endblock %}

{% block body %} 

{% load humanize %}
<div class="container">
    <h1>Are you sure you want to delete room {{ room.pk }}?</h1>
    <form method = 'POST'>
        {% csrf_token %}
        <input type = 'submit' value = 'Delete' class = 'btn btn-danger'>
        <a href="{% url 'hotel:room_in_detail' pk=room.pk %}" class='btn btn-success'>No</a>
    </form>    
</div>
{% endblock %}

advanced/hotel/templates/hotel/room_form.html
{% extends 'hotel/hotel_base.html' %}

{% block title %} Create / Update {% endblock %}

{% block body %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header">
                    <h1>
                        {% if not form.instance.pk %}
                        Create Room
                        {% else %}
                        Update Room
                        {% endif %}
                    </h1>
    
                </div>
                <div class="card-body">
                    <form method='POST' novalidate>
                        {% csrf_token %}
                        {{form|crispy}}
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </div>
            </div>
    
        </div>
    </div>
</div>

{% endblock %}

advanced/hotel/templates/hotel/room_list.html
{% extends 'hotel/hotel_base.html' %}

{% load humanize %}


{% block title %} Rooms List {% endblock %}

{% block body %}

<div class="header">
    <h1 class = 'display-3'>Room List </h1>
</div>

<div class="row mt-4">
    <div class="col-sm-1"></div>
    <div class="col-sm-8">
        {% if rooms %} <!--?If there are rooms; show them in a table-->
            <table class="table table-striped table-inverse table-responsive">
                    <tbody>
                        {% for group,roomz in groups.items %}
                        <tr>
                            <!-- <td scope="row">{{ group|apnumber|upper }}</td> -->
                            {% for room in roomz %}
                                <td class="py-4">
                                    <a class="btn btn-light" href="rooms/{{room.pk}}" data-toggle="tooltip" data-placement="" title="Room {{room}} details">
                                        Room <br> {{ room }}
                                    </a>
                                </td>
                            {% endfor %}
                        </tr>
                        {% endfor %}                            
                    </tbody>
            </table>
            
            {% else %} <!--If there are no rooms-->
            <h1>There are currently no registered rooms</h1>
            {% endif %}
        </div>
        
        <div class="col-sm-3 ">
            <div id = "actions" class="card">
                <div class = "card-header">
                    <h2 class = "display-3">Actions</h2>
                </div>
                <div class="card-body">
                    <a href='{% url "hotel:create_room" %}' class="btn btn-dark m-3 p-2 ">
                        Add Room <span class="badge "><i class="fas fa-arrow-circle-right" aria-hidden="true"></i></span>
                    </a>
                    <a href='#' class="btn btn-dark m-3 p-2 ">
                        Action <span class="badge "><i class="fas fa-arrow-circle-right" aria-hidden="true"></i></span>
                    </a>
                    <a href='#' class="btn btn-dark m-3 p-2 ">
                        Action <span class="badge "><i class="fas fa-arrow-circle-right" aria-hidden="true"></i></span>
                    </a>
                    <a href='#' class="btn btn-dark m-3 p-2 ">
                        Action <span class="badge "><i class="fas fa-arrow-circle-right" aria-hidden="true"></i></span>
                    </a>
                </div>
            </div>
        </div>

    </div>



{% endblock %}

advanced/hotel/templates/hotel/rooms_details.html
{% extends 'hotel/hotel_base.html' %}

{% block title %} Rooms In Detail {% endblock %}

{% block body %}
<div class="container">

    <h1>Showing details for <em>Room {{room_in_detail.number}}</em> </h1>
    
    <p><b>Floor:</b> {{room_in_detail.floor}}</p>
    <p><b>Capacity:</b> {{room_in_detail.capacity}}</p>
    
    
    {% if room_in_detail.tenants.all %}
        
        <h2>Occupants</h2>
        <table class="mt-4 table table-striped table-inverse table-responsive">
            <thead class="thead-inverse">
                <tr>
                    <th>Student ID</th>
                    <th>Name</th>
                    <th>Level</th>
                    <th></th>
                </tr>
            </thead>
                <tbody>
                    {% for tenant in room_in_detail.tenants.all %}
                    <tr>
                        <td scope="row">{{tenant.student_ID}}</td>
                        <td>{{tenant|title}}</td>
                        <td>{{tenant.level}}</td>
                        <td>
                            <a href="{% url 'hotel:delete_tenant' pk=tenant.pk%}?room={{room_in_detail.pk}}">
                                <button type="submit"class="btn btn-danger">
                                    <i class="fas fa-walking"></i> <i class="fas fa-door-open"></i>
                                </button>
                            </a>
                            <a href="{% url 'hotel:delete_tenant' pk=tenant.pk%}?room={{room_in_detail.pk}}">
                                <button type="submit" class="btn btn-success">
                                    <i class="fas fa-redo"></i>
                                </button>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
        </table>
    
    {% else %}
        <p>There are currently no students in this room</p>
    {% endif %}
    
    
    {% if room_in_detail.tenants.all|length < room_in_detail.capacity %}
        <!--? "room" as used below becomes a variable in the url--> 
        <a href='{% url "hotel:create_tenant" pk=room_in_detail.pk %}?room={{room_in_detail.pk}}'class="btn btn-primary"> 
            Add Tenant <span class="badge badge-primary"> -> </span>
        </a>
    
    {% else %}
    
    <p><i>The room has reached its full capacity</i></p>
    
    {% endif %}
        
    
        <a href="{% url 'hotel:delete_room' pk=room_in_detail.pk%}"><button type="submit" class="btn btn-danger">Delete Room</button></a>
</div>


{% endblock %}

advanced/hotel/templates/hotel/tenant_confirm_delete.html
{% extends 'hotel/hotel_base.html' %}

{% block title %} remove Tenant {% endblock %}

{% block body %}

{% load humanize %}
<div class="container">
    <h1>Are you sure you want to remove {{ tenant.name }} from room {{ tenant.room }}?</h1>
    <form method='POST'>
        {% csrf_token %}
        <input type='submit' value='Delete' class='btn btn-danger'>
        <a href="{% url 'hotel:room_in_detail' pk=tenant.room.pk %}" class='btn btn-success'>No</a>
    </form>
</div>
{% endblock %}

advanced/hotel/templates/hotel/tenant_form.html
{% extends 'hotel/hotel_base.html' %}

{% block title %} Create / Update {% endblock %}

{% block body %}

{% load crispy_forms_tags %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header">
                    <h1>
                        {% if not form.instance.pk %}
                        Add Tenant
                        {% else %}
                        Update Tenant Details
                        {% endif %}
                    </h1>
                </div>
                <div class="card-body">
                    <form method='POST' novalidate>
                        {% csrf_token %}
                        {{form|crispy}}
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>        
</div>

{% endblock %}