advanced/advanced/urls.py
from django.contrib import admin
from django.urls import path,include
from hotel import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name = 'home'),
    path('hotel/', include('hotel.urls', namespace = 'hotel')),
    path('accounts/login/', auth_views.LoginView.as_view(), name = 'login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('accounts/register/', views.ManagerRegister.as_view(), name = 'register')
]   

advanced/hostel/urls.py
from django.urls import path, re_path
from hostel import views

app_name = 'hostel'

urlpatterns = [
    path('', views.RoomsListView.as_view(), name = 'rooms'),
    path('create_room/', views.RoomsCreateView.as_view(), name = 'create_room'),
    re_path(r'^room(?P<pk>\w+)/create_tenant/$', views.TenantsCreateView.as_view(), name = 'create_tenant'),
    re_path(r'^room(?P<pk>\w+)/$', views.RoomsDetailView.as_view(), name = 'room_in_detail'),
    re_path(r'^update/(?P<pk>\w+)/$', views.RoomsUpdateView.as_view(), name = 'update'),
    re_path(r'^delete/(?P<pk>\w+)/$', views.RoomsDeleteView.as_view(), name = 'delete'),
]

advanced/hotel/urls.py
from django.urls import path, re_path
from hotel import views

app_name = 'hotel'

urlpatterns = [
    # rooms urls
    path('', views.RoomsListView.as_view(), name = 'rooms'),
    path('create_room/', views.RoomsCreateView.as_view(), name = 'create_room'),
    re_path(r'^rooms/(?P<pk>\w+)/$', views.RoomsDetailView.as_view(), name = 'room_in_detail'),
    re_path(r'^update/(?P<pk>\w+)/$', views.RoomsUpdateView.as_view(), name = 'update_room'),
    re_path(r'^delete_room(?P<pk>\w+)/$', views.RoomsDeleteView.as_view(), name = 'delete_room'),
    # tenants urls
    re_path(r'^room(?P<pk>\w+)/create_tenant/$', views.TenantsCreateView.as_view(), name = 'create_tenant'),
    re_path(r'^delete_tenant/(?P<pk>\w+)/$', views.TenantsDeleteView.as_view(), name = 'delete_tenant'),
    
]

advanced/hostel/models.py
from django.db import models
from django.core import validators
from django.urls import reverse

# Create your models here.
class Room(models.Model):
    floor = models.CharField(max_length = 256)
    capacity = models.PositiveIntegerField(validators = [validators.MaxValueValidator(4,'Must not exceed 4 members')])

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse("hostel:room_in_detail", kwargs={"pk": self.pk})
    


class Tenant(models.Model):
    name = models.CharField(max_length = 100)
    level = models.PositiveIntegerField()
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name = 'tenants')
    # * student_id

    def __str__(self):
        return self.name 

    def get_absolute_url(self):
        return reverse("hostel:room_in_detail", kwargs={"pk": self.room.pk})

advanced/hostel/forms.py
from django import forms
from hostel.models import Tenant

class NewTenantForm(forms.ModelForm):    
    class Meta:
        model = Tenant
        exclude = ('room',) # todo: to prevent editing value in the html (hackily)
        #// widgets = {
        #//     'room' : forms.HiddenInput(attrs={'readonly':True}),
        #// }
        

advanced/hostel/views.py
from django.shortcuts import render
from hostel.models import Tenant, Room
from django.views.generic import ListView, DetailView,TemplateView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from hostel.forms import NewTenantForm
from django.http import request

# Create your views here.
class HomeView(TemplateView):
    template_name = 'home.html'


class RoomsListView(ListView):
    model = Room
    context_object_name = 'rooms'


class RoomsDetailView(DetailView):
    model = Room
    context_object_name = 'room_in_detail'
    template_name = 'hostel/rooms_details.html'


class RoomsCreateView(CreateView):
    model = Room
    fields = '__all__'


class RoomsUpdateView(UpdateView):
    model = Room
    fields = '__all__'
    

class RoomsDeleteView(DeleteView):
    model = Room
    success_url = reverse_lazy('hostel:rooms')
    

class TenantsCreateView(CreateView):
    model = Tenant
    form_class = NewTenantForm #? the form_class attribute allows replacement of default CreateView form

    def form_valid(self, form):
        # todo: getting the 'room' variable from the GET request (I created the variable in the url coming to this view)
        room_num = self.request.GET.get('room')
        # todo: setting the current modelform object's room field to the value got from above
        form.instance.room = Room.objects.get(id=room_num)
        return super(TenantsCreateView, self).form_valid(form)

    #// # todo: pre-fill form data
    # ! this is inefficient as hidden inputs can be edited hackily (even with readonly attribute)
    #// """
    #// ?get_initial is a method that needs to be overrided in order to pre-fill form data
    #// ?it returns a dictionary with keys as form fields and values representing intended prefilled data
    #// """
    #// def get_initial(self):  
    #//     room = self.request.GET.get('room') #todo: getting the 'room' variable from the GET request (I created the variable in the url coming to this view) 
    #//     # print(self.request.GET)
    #//     return {
    #//         'room':room,
    #//     }

advanced/hostel/templates/hostel/hostel_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %} Hostel | Base {% endblock %}</title>

    <link rel="stylesheet" href="{% static 'bs4/css/bootstrap.min.css' %}">

</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <ul class="navbar-nav nav">
            <li class="nav-item"><a href="{% url 'hostel:rooms' %}" class="navbar-brand">Rooms</a></li>
            <li class="nav-item"><a href="{% url 'admin:index' %}" class="nav-link">Admin</a></li>
        </ul>
    </nav>

    <div class="container mt-4">
        {% block body %}{% endblock %}
    </div>
</body>

</html>

advanced/hostel/templates/hostel/room_confirm_delete.html
{% extends 'hostel/hostel_base.html' %}

{% block title %} Delete Room {% endblock %}

{% block body %} 

{% load humanize %}
<h1>Are you sure you want to delete room {{ room.id|apnumber }}?</h1>
<form method = 'POST'>
    {% csrf_token %}
    <input type = 'submit' value = 'Delete' class = 'btn btn-danger'>
    <a href="{% url 'hostel:room_in_detail' pk=room.pk %}" class='btn btn-success'>No</a>
</form>
{% endblock %}

advanced/hostel/templates/hostel/room_form.html
{% extends 'hostel/hostel_base.html' %}

{% block title %} Create / Update {% endblock %}

{% block body %}

<h1>
{% if not form.instance.pk %}
Create Room
{% else %}
Update Room
{% endif %}
</h1>

<form method = 'POST'>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Create</button>
</form>

{% endblock %}

advanced/hostel/templates/hostel/room_list.html
{% extends 'hostel/hostel_base.html' %}

{% load humanize %}

{% block title %} Rooms List {% endblock %}

{% block body %}

{% if rooms %}

    <h1>Here are the currently occupied rooms:</h1>
    <ol>
        {% for room in rooms %}
            <h2>
                <li><a href="room{{ room.id }}">{{room.id|ordinal|title}}</a></li>
            </h2>
        {% endfor %}
    </ol>

{% else %}
    <h1>There are currently no occupied rooms</h1>
{% endif %}

<a href='{% url "hostel:create_room" %}' class="btn btn-primary">
    Add Room <span class="badge badge-primary">-></span>
</a>


{% endblock %}

advanced/hostel/templates/hostel/rooms_details.html
{% extends 'hostel/hostel_base.html' %}

{% block title %} Rooms In Detail {% endblock %}

{% block body %}

<h1>Showing details for <em>Room:{{room_in_detail.id}}</em> </h1>

<p>Floor: {{room_in_detail.floor}}</p>
<p>Capacity: {{room_in_detail.capacity}}</p>

<h2>Students in Room:</h2>
<table class="table table-striped table-inverse table-responsive">
    <thead class="thead-inverse">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Level</th>
        </tr>
    </thead>
        <tbody>
            {% for tenant in room_in_detail.tenants.all %}
            <tr>
                <td scope="row">{{tenant.id}}</td>
                <td>{{tenant}}</td>
                <td>{{tenant.level}}</td>
            </tr>
            {% endfor %}
        </tbody>
</table>

<!--? "room" as used below becomes a variable in the url--> 
<a href='{% url "hostel:create_tenant" pk=room_in_detail.pk %}?room={{room_in_detail.pk}}'class="btn btn-primary"> 
    Add Tenant <span class="badge badge-primary"> -> </span>
</a>

<a href="{% url 'hostel:delete' pk=room_in_detail.pk%}"><button type="submit" class="btn btn-danger">Delete Room</button></a>


{% endblock %}

advanced/hostel/templates/hostel/tenant_form.html
{% extends 'hostel/hostel_base.html' %}

{% block title %} Create / Update {% endblock %}

{% block body %}

<h1>
    {% if not form.instance.pk %}
    Add Tenant
    {% else %}
    Update Tenant Details
    {% endif %}
</h1>

<form method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Create</button>
</form>

{% endblock %}