advanced/advanced/urls.py
from django.contrib import admin
from django.urls import path,include
from hotel import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name = 'home'),
    path('hotel/', include('hotel.urls', namespace = 'hotel')),
    path('accounts/login/', auth_views.LoginView.as_view(), name = 'login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('accounts/register/', views.ManagerRegister.as_view(), name = 'register')
]   

advanced/hotel/urls.py
from django.urls import path, re_path
from hotel import views

app_name = 'hotel'

urlpatterns = [
    # rooms urls
    path('', views.RoomsListView.as_view(), name = 'rooms'),
    path('create_room/', views.RoomsCreateView.as_view(), name = 'create_room'),
    re_path(r'^rooms/(?P<pk>\w+)/$', views.RoomsDetailView.as_view(), name = 'room_in_detail'),
    re_path(r'^update/(?P<pk>\w+)/$', views.RoomsUpdateView.as_view(), name = 'update_room'),
    re_path(r'^delete_room(?P<pk>\w+)/$', views.RoomsDeleteView.as_view(), name = 'delete_room'),
    # tenants urls
    re_path(r'^room(?P<pk>\w+)/create_tenant/$', views.TenantsCreateView.as_view(), name = 'create_tenant'),
    re_path(r'^delete_tenant/(?P<pk>\w+)/$', views.TenantsDeleteView.as_view(), name = 'delete_tenant'),
    
]

advanced/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>{% block title %} Base {% endblock %}</title>

    <link rel="stylesheet" href="{% static 'bs4/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome-free-5.10.1-web/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'hotel.css' %}">

    <script src='{% static "fontawesome-free-5.10.1-web/js/all.min.js" %}'></script>

</head>
<body>
    <div id="content">
        <nav class="navbar navbar-expand-sm navbar-light bg-light">
            <ul class="navbar-nav nav">
                <li class="nav-item"><a href="{% url 'hotel:rooms' %}" class="navbar-brand">Rooms</a></li>
                <li class="nav-item"><a href="{% url 'admin:index' %}" class="nav-link">Admin</a></li>
                <!-- <li class="nav-item"><a href="{% url 'admin:index' %}" class="nav-link">Admin</a></li> -->
            </ul>
        </nav>

        <div class="container mt-4 ">
            {% block body %}{% endblock %}
        </div>
        <footer>
            <i class="far fa-copyright"></i> <b>Works of Machele-codez(Codesmith)</b>, Powered by Django 2.2.7
        </footer>
    </div>

</body>

</html>

advanced/templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block body %} 

<div class="jumbotron mt-4">
    <h1 class="display-2">
        Hotel Administration Page!
    </h1>
</div>
<a class = 'btn btn-primary' href="{% url 'hotel:rooms' %}">View Rooms</a>

{% endblock %}